language: php
php:
- 7.1
addons:
  ssh_known_hosts: 78.45.212.91
  apt:
    packages:
    - sshpass openssh-client
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - ls

deploy:
  provider: releases
  file: phinx.yml
  skip_cleanup: true
  on:
    tags: false